### ISSUE TITLE
Crypto-native to use same parallax fx that MG site has today

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#21]
## Description
The **[Crypto Native](https://www.miragegallery.ai/crypto-native)** page has a parallax effect when showing the steps of the creation process.

We need to add the remaining images to the new [Crypto Native](https://mirage-gallery.vercel.app/crypto-native) page with the same effect.

**Comment by santuan** [comment]
Fix in commit 6b24f92a53b32377181bbc9671aa9ae45413e928

**Comment by tomasg88** [comment]
merged to release
