### ISSUE TITLE
Dynamic gallery in Curated page

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#22]
## Description
The new Curated page has a grid of images. It would be good that the grid could be updated. For example with the currently `minting` Drops, or the `upcoming` ones. 

There are 2 tasks we need to research to make this grid look and work properly.

1. How shall we preserve aspect ratios regardless of the position they are shown in the grid?
2. Images are too heavy, because they are artworks. So, how do we make images download faster?

**Comment by tomasg88** [comment]
Since each drop will be loaded with up to 8 samples of art, the 1st one will be the one used as cover. Also, that 1st sample will be used as the top hero image in the details of that drop.

Is there a specific order in which we should show the drops? createdAt, updatedAt, status...

**Comment by tomasg88** [comment]
@augustfr see last question pls. what do you think about the order?

**Comment by augustfr** [comment]
Let's show them in order of dates. Newest at the top.
