### ISSUE TITLE
Allow trackpad to scroll horizontally in home page gallery

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#23]
## Description
There is a slider in the [home page](https://mirage-gallery.vercel.app) that shows images. It would be nice if we could trigger the left and right scrolling with a swipe in the Mac Os trackpad

**Comment by santuan** [comment]
Fix in commit 6b24f92a53b32377181bbc9671aa9ae45413e928

**Comment by tomasg88** [comment]
merged to `release`
