### ISSUE TITLE
Add Mint functionality

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#31]
## Description
Similar to #30 but calling another contract for Minting. Another change of fields has to be done in the html as well.

### Changes
Same as in #30 there is a tab called **Mint** in the drop details.
1. Quantity field is the only field in the form
2. Mint button should call the smart contract and pass Project Id (`drop.project.id`) and the Quantity (from the html)

### Possible outcomes
Same as #30 .

**Comment by tomasg88** [comment]
@augustfr this could be a good place to add info on the Minting service, thankx

**Comment by augustfr** [comment]
Let me know if there is any specific info you need. https://github.com/Mirage-Gallery/mirage-minting/blob/main/src/pages/abstract-artchitecture.js.

That code shows the basic implementation of presale and public sale minting for a single curated drop.
