### ISSUE TITLE
Show date a shorter format on non-sold out curated pages.

### ISSUE THREAD

**Issue by augustfr** [tomasg88/mirage-gallery#68]
For example right now it shows. Mon Mar 27 2023 09:30:00 GMT-0700 (Pacific Daylight Time).

Ideally, it would show:

Monday, March 27th, 2023
Presale: 9:30am PDT
Public sale: 10:30am PDT (public sale should just be one hour after the date from sanity)

**Comment by tomasg88** [comment]
We have only one field for release date. is that for public or pre sale?

**Comment by augustfr** [comment]
This is for presale. Public sale is 1 hour after.
